{
    'username': 'admin',
    'password' : 'admin'
}


(Valid for 7 days)
jwt_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ0NDQzMTU0LCJleHAiOjE3NDUwNDc5NTR9.QQhUIEZ-2X_zKlp_TbJjz74N2v5pJkGyL9_vIjtQM4s

